# Generated by Django 2.1.2 on 2018-11-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20181130_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvmodel',
            old_name='url_list',
            new_name='url_lists',
        ),
    ]
