# Generated by Django 2.1.5 on 2019-03-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_zongyimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
