# Generated by Django 2.1.5 on 2019-03-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_category_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoonmodel',
            name='video',
            field=models.CharField(default=11, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='video',
            field=models.CharField(default='11', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvmodel',
            name='video',
            field=models.CharField(default='11', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zongyimodel',
            name='video',
            field=models.CharField(default='movie', max_length=10),
        ),
    ]
